### ISSUE TITLE
Unknown function "API"

### ISSUE THREAD

**Issue by jclaudino** [brentadamson/dataconnector#5]
Hi, I've been using this plugin for a few months now and it's been fantastic, thank you! However, this latest update has resulted in my sheet no longer recognizing the "API" function, and my saved queries have all disappeared. 

Did the function name change to something new? I've tried re-installing the plugin to no avail. As someone else mentioned, some updated documentation would be much appreciated as well.

**Comment by brentadamson** [comment]
Hi,

Sorry for breaking you! I think that open sourcing everything will ultimately lead to a better Add-on. I decided to replace the =api() function with =run(), since I plan on connecting to more than just APIs (databases, etc). You should be able to re-create your commands and be good to go. The old docs at https://apiimporter.com/ still generally apply, except replace =api() with =run(). I have https://github.com/brentadamson/dataconnector/issues/1 open and that is my priority now.

**Comment by jclaudino** [comment]
Thanks for the reply, run() did the trick!

Can you remind me how to pass extra params from the run() function into the query params of the API request? I got it working a few months back but can't recall the trick.

**Comment by brentadamson** [comment]
Oh, yeah. I forgot that that part is in the old FAQ that I haven't migrated over yet. To include parameters, stick the `+++1+++` pattern in your command (the URL path, query, headers, etc). For a second parameter you'd put `+++2+++` and so on. Now, when you call the `=run()` function you'd do:

```
=run("my_command", "AAPL", "MSFT")
```

Where "AAPL" would be the first parameter and "MSFT" the second.

If you have params in your command but forget to pass them in the `=run()` function you'll get an error reminding you that you have unhandled params.

**Comment by jclaudino** [comment]
Ahh that's right, I thought it was {{{1}}} for some reason. I'm back in action, thanks again! And thanks for building this and open sourcing it, I tried half a dozen others that were all harder to work with and wanted $ for basic functionality. Your tool was a lifesaver!

**Comment by brentadamson** [comment]
Closing. I've added some docs and linked to them from the Add-on. If you'd like to add instructions for a particular API then please open up another issue. Thanks!
